name: Duckdb and core tests
on:
  push:
  pull_request:
    branches:
      - master
      - "**dev"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13"]
    name: Run tests with Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4

      - name: Install poetry using pipx
        run: pipx install poetry

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"

      - name: Install dependencies
        run: |
          poetry config virtualenvs.in-project true
          poetry install --no-interaction --no-root

      - name: Run tests with coverage
        run: |
          poetry add "pytest-cov>=5.0.0"
          poetry run pytest -v --durations=0 -m "duckdb_only or core" --cov=splink --cov-report=xml --cov-report=term tests/

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: coverage.xml
